version: '2'
services:
  staticman:
    build: .
    env_file: .env
    ports:
      - '8080:8080'
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 8080
      GITHUB_TOKEN: #insert your GitHub token here
      RSA_PRIVATE_KEY: |
        -----BEGIN RSA PRIVATE KEY-----
        
        -----END RSA PRIVATE KEY-----        